### ISSUE TITLE
RetroArch: look for palmos rom in system directory

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#57]
as title

The way I would expect it working would be:

1. start core
2. look for palmos41-en-m515.rom in RetroArch system directory
3. accept PRC file types, temporarily copy them into RAM and launch

It's odd, but given my experience with the PX68k core, RetroArch users do not seem to want persistent devices (even if that's how they are IRL) but rather a core as a device for running a game/app in demand.

**Comment by meepingsnesroms** [comment]
Done, "Start Core" loads the standard device and loading content boots to the homescreen with the app installed.

**Comment by gingerbeardman** [comment]
Thank you
