### ISSUE TITLE
RetroArch: accept/load PRC filetype

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#58]
as title.

The way I would expect it working would be:

1. start core
2. look for palmos41-en-m515.rom in RetroArch system directory
3. accept PRC file types, temporarily copy them into RAM and launch

It's odd, but given my experience with the PX68k core, RetroArch users do not seem to want persistent devices (even if that's how they are IRL) but rather a core as a device for running a game/app in demand.

**Comment by meepingsnesroms** [comment]
Done, may still be buggy but it loads.

**Comment by gingerbeardman** [comment]
Thanks again!

**Comment by paradadf** [comment]
@meepingsnesroms do we need to compile the core with `EMU_HAVE_FILE_LAUNCHER=1` for libretro?

**Comment by parkerlreed** [comment]
@paradadf No. The default compile works fine.
