### ISSUE TITLE
Blank window running RamBuilder Mu.exe

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#59]
## Describe the bug in detail and how to reproduce it.  

0. https://github.com/meepingsnesroms/Mu/releases/tag/v1/3x3
1. Follow `HowToUseRamBuilder.txt`
2. Use included Mu.exe

## Results
- Windows 7 (32-bit)
![screen shot 2019-02-12 at 12 54 42](https://user-images.githubusercontent.com/49612/52637506-47d4aa80-2ec7-11e9-9981-af1dfc4c43a5.png)
- Windows 10 (64-bit)
![screen shot 2019-02-12 at 12 54 42](https://user-images.githubusercontent.com/49612/52637497-41dec980-2ec7-11e9-8638-dcfd8b8715d9.png)
- Wine/CrossOver
![screen shot 2019-02-12 at 13 07 49](https://user-images.githubusercontent.com/49612/52637517-502ce580-2ec7-11e9-9832-4020768ffa43.png)

## Upload your "userdata-en-m515.ram" if you can.  
n/a

## List your OS, whether you are using the Qt or RetroArch build, the version of the build you are using, 
See above.

## and the MD5 checksum of your "palmos41-en-m515.rom".  

palmos41-en-m515.rom: 412557a221933a8be12622de7a21320a (MD5) 

and

palmos41-en-m515.rom: 83cb1d1c76e568b916dc2e7c0bf669f6 (MD5)
bootloader-en-m515.rom: 9da101cd2317830649a31f8fa46debec (MD5)

## If you are using the RetroArch build also list your RetroArch version.
1.7.6 does at least boot the Palm ROM that I have.

![screen shot 2019-02-12 at 13 10 32](https://user-images.githubusercontent.com/49612/52637606-9d10bc00-2ec7-11e9-9bd9-aa4bbad6ea1f.png)

**Comment by gingerbeardman** [comment]
Oh, crap. My fault. 🙈

> 4. Run emu and _press start button_

I guess the "start button" really needs to be more visible (and maybe automatic)? Right now it looks disabled.

The clue was Wine putting the dotted highlight around the button.

**Comment by parkerlreed** [comment]
FWIW you don't need WINE. The RAM builder is the standalone compiled with debug.
````
cd qtBuildSystem/Mu/
qmake CONFIG+=debug
make -j5
./Mu
````

**Comment by gingerbeardman** [comment]
Awesome! That worked a treat with `./Mu.app` as final step

**Comment by gingerbeardman** [comment]
@parkerlreed spoke to soon, it builds and runs but gets stuck on Palm logo?

**Comment by gingerbeardman** [comment]
@parkerlreed building without the debug gets me a Mu.app I can use to do stuff.

I'll inject apps using Wine for now.
