### ISSUE TITLE
Support for Japanese

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#60]
Japanese ROMs I am aware of
- 3.1 
  - palmv31-jp.rom MD5:	 acc2911865c2beea7244e1f431ea6bba
- 5.4
  - Simulator_Full_jpJP_Release.rom MD5:	 6346c6da7f6e46c3b605d3239e65d4c8
- Clie
  - ​N700C_jp.rom MD5:	 3771d63e3b732cad92ba812a0fdbb44a

None of these work with Mu at the moment.

But, my goal is to play this game: 掌花札 (Palm Hanafuda)

The game plays but the text is not readable.

1. https://web.archive.org/web/20041204170805/http://muchy.com/review/tenohirahanafudapagj.html
2. https://web.archive.org/web/20041204110330/http://muchy.com/review/tenohirahanafuda.html
(you can only install one of these at a time)

## Goal (from game 1)
![image](https://user-images.githubusercontent.com/49612/52641609-25478f00-2ed1-11e9-94d5-adb2a6511c99.png)

## Currently (from game 2)
![screen shot 2019-02-12 at 14 09 00](https://user-images.githubusercontent.com/49612/52641730-6c358480-2ed1-11e9-898b-c1e2f1e1da06.png)

**Comment by meepingsnesroms** [comment]
Does this fix it?
https://palmdb.net/930/cjkos/

If it doesnt I will look into copying some language packs over from a different ROM, this is rather high priority as I am learning Japanese.

**Comment by gingerbeardman** [comment]
I'll try soon and report back. 

I learned a little Japanese a while back. Great fun!

**Comment by gingerbeardman** [comment]
So CKOS works — cool! It seems it has a 30 day trial limit?

1. unzip `cjkos_os4.zip`
2. install `CJKOS.prc`
3. (optional) install `cManager.prc` (font manager)
4. unzip `cjkFontL.zip`
5. install `FontFJIS10L.PDB` (10x10 font)

My only comment would be that it's not as legible as the official Japanese font.

For example
- app name
- size of all Japanese characters

So you can install additional fonts: http://palm.roguelife.org/cjkos/
I recommend Naga 10 http://palm.roguelife.org/cjkos/download/Naga_10.zip

6. uninstall `FontFJIS10L.PDB` (fonts are one-at-a-time for each size)
7. install `Naga_10.pdb`

|  Palm | CJKOS | Naga 10 |
|---|---|---|
| ![](https://user-images.githubusercontent.com/49612/52641609-25478f00-2ed1-11e9-94d5-adb2a6511c99.png) | ![screenshot2](https://user-images.githubusercontent.com/49612/52667848-e255dd80-2f09-11e9-8335-0e5c709b0f42.png) | ![screenshot3](https://user-images.githubusercontent.com/49612/52669563-3cf13880-2f0e-11e9-92c7-c46db17fbbcc.png) |

**Comment by gingerbeardman** [comment]
Just to follow on form this, there are other solutions for Japanese each with their own pros/cons. CJKOS seems like the best bet so far.

| app  | pros  | cons  |
|---|---|---|
| CJKOS  | supports hi-res, easy to register  | finding good fonts and managing them is a hassle |
| Yomeru | OS5 version on soruceforge  | OS4 version lost to time because of a missing font download |
| J-OS | works | uses other apps to achieve goal, multiple versions for different OS and devices |
| JaPon  | slick set up | does not support HiRes fonts, OS5 only |

**Comment by meepingsnesroms** [comment]
Can this be closed now?
It seems Japanese works OK and this isnt really an emu bug.

**Comment by gingerbeardman** [comment]
Sure thing!
