### ISSUE TITLE
Link to an official source of ROMs (2.0 to 3.1, all languages) 

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#61]
Not sure how legal these are?

They came with the book `PalmPilot The Ultimate Guide 2nd Edition` and the files are available here:
https://resources.oreilly.com/examples/9781565926004/tree/master/compressed_files/Palm_OS_Emulator_Win

Palm 5.4 Simulator contained some:
https://palmarchive.com/files/?dir=LukeLC%27s%20Archive/Simulator/PalmOS%20Garnet%205.4%20Simulator/Release

NOTE: These do not currently work with Mu.

**Comment by parkerlreed** [comment]
Probably never will. Mu targets one particular device (m515). This isn't a general emulator like POSE.

**Comment by gingerbeardman** [comment]
Ah, I see. Thanks!
