### ISSUE TITLE
Game crash report

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#62]
## Describe the bug in detail and how to reproduce it.  

1. launch Koi-Koi (B&W icon)
2. Press "start"

## Crash
I suspect it needs Japanese ROM 3.1?

![screen shot 2019-02-12 at 14 27 27](https://user-images.githubusercontent.com/49612/52642158-5b394300-2ed2-11e9-8898-be77b740e233.png)

## Upload your "userdata-en-m515.ram" if you can.  
[userdata-en-m515.ram.zip](https://github.com/meepingsnesroms/Mu/files/2856212/userdata-en-m515.ram.zip)

## List your OS, whether you are using the Qt or RetroArch build, the version of the build you are using, 
- RetroArch 1.7.6
- Mu.exe in RamBuilder running in Wine/CrossOver

## and the MD5 checksum of your "palmos41-en-m515.rom".  

palmos41-en-m515.rom: 83cb1d1c76e568b916dc2e7c0bf669f6 (MD5)
bootloader-en-m515.rom: 9da101cd2317830649a31f8fa46debec (MD5)

## Game
- https://web.archive.org/web/20041204172016/http://muchy.com/review/koikoi.html
- download using ` [今すぐダウンロード!]` link next to app/game version number

**Comment by meepingsnesroms** [comment]
Fixed by adding support for black and white hardware: https://github.com/meepingsnesroms/Mu/commit/2ece2d56d4a7e14e4bdf36580db8a0dd579727b1
