### ISSUE TITLE
Mu.exe map controls to keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#63]
Currently cursor moves the focus around the buttons, and you have to click with the mouse or press space.

I have got around this by using external software to map key presses to mouse clicks, but it would be great if it was built-in.

**Comment by meepingsnesroms** [comment]
Done:
https://github.com/meepingsnesroms/Mu/commit/6b81ca4cc01708598bf7a41646123223552415fb

**Comment by gingerbeardman** [comment]
Thanks
