### ISSUE TITLE
RetroArch: Nintendo 3DS does not support touch?

### ISSUE THREAD

**Issue by gingerbeardman** [meepingsnesroms/Mu#64]
I'd love to play this on Nintendo 3DS, with device rotated 90' so it's using the touch screen 

It only displays on the top screen at the moment so there is no touch?

**Comment by meepingsnesroms** [comment]
This is a RetroArch bug:
https://github.com/libretro/RetroArch/issues/5946
https://github.com/libretro/RetroArch/issues/2508
