### ISSUE TITLE
Installing PRC file.

### ISSUE THREAD

**Issue by kkszysiu** [meepingsnesroms/Mu#73]
Hey guys,

So I've compiled Mu with QT interface on macOS.
The system is running fine.

<img width="372" alt="Screenshot 2019-05-05 at 19 15 38" src="https://user-images.githubusercontent.com/70684/57197645-37821800-6f6a-11e9-9eea-ab336010bdc0.png">

Now I need to install PRC file to see how it works.
As I understand all I should do is click this button:
<img width="77" alt="Screenshot 2019-05-05 at 19 16 24" src="https://user-images.githubusercontent.com/70684/57197656-4a94e800-6f6a-11e9-8436-99d3720a5386.png">
Then select a PRC file and it's done, or am I missing something?
I do not see this app in the apps menu after this process. Actually nothing is happening after that...

I'm new into PalmOS, I just need it to check how the app works.

PRC file:
[mmcd-1.5d.zip](https://github.com/meepingsnesroms/Mu/files/3145838/mmcd-1.5d.zip)

**Comment by parkerlreed** [comment]
The application has to be compiled in debug for the prc installer to work.

**Comment by meepingsnesroms** [comment]
The installer is now always enabled and a boot option has been added, still needs a bit of gui work though.
