### ISSUE TITLE
Change retroarch button mapping

### ISSUE THREAD

**Issue by paradadf** [meepingsnesroms/Mu#85]
Using palmos41-en-m515.rom and Retroarch's build.

The current mapping isn't optimal for playing games, as pressing retropad A would move left and retropad B would move right.

<img width="139" alt="palm_buttons" src="https://user-images.githubusercontent.com/15956550/58666049-4907d700-8300-11e9-8c7b-d654612cbb2a.png">

I've tested many games and all of them used the **Date Book** to move LEFT and **Address Book** to move Right. So I'd suggest to change the current mapping between these two:
https://github.com/meepingsnesroms/Mu/blob/master/libretroBuildSystem/libretro.c#L230-L231

That way, `RETRO_DEVICE_ID_JOYPAD_A` would be `Address Book` and `RETRO_DEVICE_ID_JOYPAD_B` would be `Date Book`

**Comment by meepingsnesroms** [comment]
How is this:
https://github.com/meepingsnesroms/Mu/commit/29ca09302fadf999494dfef8c200c5217caf33f7
The left 2 buttons on the Palm are the top 2 bottons on the SNES controller, YX(Y is the button to the left just like on the SNES controller), the bottom buttons are the right 2, also left right aligned.
Can you test this layout?

**Comment by paradadf** [comment]
I‘ll test it asap. Thank you very much!

**Comment by paradadf** [comment]
Much better! I can live with that! Thank you very much!

**Comment by meepingsnesroms** [comment]
Ok will update the overlay then merge this commit over.

**Comment by paradadf** [comment]
Is there any particular reason why the touchscreen touch is mapped to R2 instead of R1?

**Comment by meepingsnesroms** [comment]
In case people want to map L1/R1 as some app buttons, do you want that changed too?
That is actually easy to change.

**Comment by paradadf** [comment]
Now that we are at it, yes. :) it would make smaller gamepads function ootb.

**Comment by meepingsnesroms** [comment]
OK

**Comment by meepingsnesroms** [comment]
Done

**Comment by paradadf** [comment]
Great. Thank you! When everything reaches the master branch, I think it will be ready for integration. Lets see how long until users start complainig!

**Comment by meepingsnesroms** [comment]
Done, merged, waiting for builds.
